version: "3.5"

networks:
  pushme-net:
    name: pushme-net

services:
  postgres:
    image: postgres:13.4-buster
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - pushme-net

  pushme:
    image: pushme_server:local
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - pushme-net
