version: "3.5"

networks:
  pushme-net:
    name: pushme-net

services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.data:/config
    restart: unless-stopped
    networks:
      - pushme-net

  pushme:
    image: pushme_server:local
    build:
      context: .
    depends_on:
      - mariadb
    environment:
      NODE_ENV: production
      DATABASE_URL: mariadb://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
    networks:
      - pushme-net
    restart: unless-stopped
